### ISSUE TITLE
/delete does not work

### ISSUE THREAD

**Issue by Matic0B** [AltitudeMapdev/Issues#68]
Using only "/delete" will attempt to delete world "matic0basle" but theres no world "matic0basle" because I have worlds renamed.
Then trying "/delete matic0basle2" gives the "You don't have permission." text even tho its my world.

**Comment by gcflames5** [comment]
@matic0basle  Are you a default user (no special perms added/removed?)

**Comment by Matic0B** [comment]
@gcflames5 Im a alpha tester. I have the green star (not sure what the rank is officialy called)

**Comment by gcflames5** [comment]
@matic0basle Fixed.

**Comment by Matic0B** [comment]
@gcflames5 Are you sure this has been fixed? I tried /delete matic0basle-1 and it gave me the message "You don't have permission". When I only did /delete it marked the world matic0basle3 for deletion even when I was in the matic0basle-1 world.

I got pepsidawg00 to delete my world because I wasnt able to do it but still seems bugged

**Comment by itsmiiolly** [comment]
the new version isn't deployed yet IIRC

**Comment by gcflames5** [comment]
@matic0basle The reason this is not fixed (well it is) but its because we are still using bukkit permissions. As long as we are using bukkit permissions and not database's these problems will persist.

@NathanTheBook has to add perms to the web panel (or give someone access so they can) and @ItsMiiOlly has to get rid of bukkit perms
